
[ClassVersion("1.0.0.0"), FriendlyName("rsDBEntry")]
class rsDBEntry : OMI_BaseResource
{
    [Key] String Key;
    [Required] String KeyColumn;
    [Required] String ConnectionString;
    [Required, EmbeddedInstance("MSFT_KeyValuePair")] String SQLData[];
    [Required] String Table;
    [Write, ValueMap{"Absent","Present"}, Values{"Absent","Present"}] String Ensure;
};

